kydi/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vote/', include('vote.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('members/', views.members, name="members"),
    path('new-member/', views.new_member, name="new_member"),
    path('update-member/', views.update_member, name="update_member"),
    path('tulinaawe/', views.tulinaawe_view, name="tulinaawe"),
    path('tulinaawe/<slug>/', views.tulinaawe_detail, name="tulinaawe_detail"),
    path('welfare/', views.welfare_view, name="welfare"),
    path('savings-withdraw/', views.savings_withdraw_view, name="savings_withdraw"),
    path('loans/', views.loans_view, name="loans"),
    path('loans/<slug>', views.loan_detail, name="loan_detail"),
    path('loan/application/', views.loan_application_view, name="loan_application"),
    path('loan/application-detail/<slug>', views.loan_application_detail_view, name="loan_application_detail"),
    path('reports/', views.reports_view, name="reports"),
    path('expenses/', views.expenses_view, name="expenses"),
    path('expenses/<slug>/', views.expenses_detail, name="expenses_detail"),
    path('notes/', views.notes_view, name="notes"),

    path('<slug>/<slug2>-new-transaction/', views.member_new_transaction, name='member_new_transaction'),
    path('<slug>/<slug2>-transactions/', views.member_transactions, name="member_transactions"),

    path('<slug>/<slug2>-convert-savings/', views.convert_savings, name="convert_savings"),
    path('<slug>/<slug2>-pay-using-shares/', views.pay_using_shares, name="pay_using_shares"),

    path('new-transaction/', views.new_transaction, name="new_transaction"),
    path('all-transactions/', views.all_transactions, name="all_transactions"),
    path('transaction/<slug>/', views.transaction_view, name="transaction"),

    path('transaction/<slug>/detail/', views.transaction_detail, name="transaction_detail"),

    path('print/', views.print_view, name="print"),

    path('member/', views.member_info, name="member_info"),

    path('member-report/', views.member_report, name="member_report"),
    path('api/reports/', views.reports_api, name="reports_api"),
    path('api/member-report/', views.member_report_api, name="member_report_api"),

    path('settings/', views.settings_view, name="settings"),
]

templates/index.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>KYDI</title>
	<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/output.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/inter/font.css' %}">
	<link rel="stylesheet" href="{% static 'client_side_image_cropping/croppie.css' %}">
    <link rel="stylesheet" href="{% static 'client_side_image_cropping/cropping_widget.css' %}">
	<link rel="stylesheet" href="{% static 'stylesheets/custom.css' %}">

	<script src="{% static 'scripts/feather.min.js' %}"></script>
	<script src="{% static 'scripts/print.min.js' %}"></script>
    <script defer src="{% static 'scripts/jquery-3.3.1.min.js' %}"></script>
    <script defer src="{% static 'client_side_image_cropping/croppie.min.js' %}"></script>
    <script defer src="{% static 'client_side_image_cropping/cropping_widget.js' %}"></script>
</head>

<body class="flex h-screen overflow-y-hidden">
	<div id="modal-container">
		{% block modal %}
		{% endblock %}
	</div>
	<aside id="nav-left" class="w-64 flex-shrink-0 h-full bg-white border-r">
		<div class="py-4 text-gray-500 h-full overflow-y-scroll">
			<h1 class="ml-6 text-lg font-bold text-gray-800">KYDI</h1>

			<ul class="block h-full mt-6 mx-3">

				<li class="relative">
					<a href="{% url 'main:dashboard' %}" class="{% block link1 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="home"></i>
						<span class="ml-4">Dashboard</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:members' %}" class="{% block link2 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="users"></i>
						<span class="ml-4">Members</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:new_member' %}" class="{% block link3 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="user-plus"></i>
						<span class="ml-4">Add Member</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:all_transactions' %}" class="{% block link4 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="layers"></i>
						<span class="ml-4">Transactions</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:new_transaction' %}" class="{% block link5 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="trending-up"></i>
						<span class="ml-4">Add Transaction</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:welfare' %}" class="{% block link13 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="smile"></i>
						<span class="ml-4">Welfare</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:savings_withdraw' %}" class="{% block link14 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="dollar-sign"></i>
						<span class="ml-4">Savings & Withdraw</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:tulinaawe' %}" class="{% block link6 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="sunrise"></i>
						<span class="ml-4">Tulinaawe</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:loans' %}" class="{% block link7 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="dollar-sign"></i>
						<span class="ml-4">Loans</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:loan_application' %}" class="{% block link11 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="folder"></i>
						<span class="ml-4">Loan Application</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:reports' %}" class="{% block link8 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="pie-chart"></i>
						<span class="ml-4">Reports</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:expenses' %}" class="{% block link9 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="shopping-bag"></i>
						<span class="ml-4">Expenses</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:notes' %}" class="{% block link10 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="file"></i>
						<span class="ml-4">Notes</span>
					</a>
				</li>

				<li class="relative">
					<a href="{% url 'main:settings' %}" class="{% block link12 %} {% endblock %}inline-flex items-center w-full text-sm font-semibold transition-colors text-gray-600 px-2 py-3 my-1">
						<i class="w-5 h-5" data-feather="settings"></i>
						<span class="ml-4">Settings</span>
					</a>
				</li>
			</ul>
		</div>
	</aside>

	<div id="main-right" class="flex flex-col flex-1 w-full overflow-x-hidden bg-bluish">
		<header class="py-4 px-4 bg-white  shadow z-10 flex justify-between items-center">
		
            {% block title %}
                <h2 class="text-sm font-semibold text-gray-700 tracking-wide">
                    KYDI MANAGEMENT SYSTEM
                </h2>
            {% endblock %}

			{% block header %}
			{% endblock %}

			<form action="{% url 'main:logout' %}" method="POST" id="logout" class="flex gap-10">
				{% csrf_token %}
				<a href="/admin" target="_blank">{{user.username}}</a>
				<button type="submit" class="flex text-sm font-semibold items-center">
					<i data-feather="log-out" class="w-4 h-4 align-middle mr-3"></i>
					<span>Logout</span>
				</button>
			</form>
			
		</header>

		{% block content %}
		{% endblock %}

	</div>
</body>
{% block scripts %}
{% endblock %}
<script>
	feather.replace();
</script>
</html>