kydi/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vote/', include('vote.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('members/', views.members, name="members"),
    path('new-member/', views.new_member, name="new_member"),
    path('update-member/', views.update_member, name="update_member"),
    path('tulinaawe/', views.tulinaawe_view, name="tulinaawe"),
    path('tulinaawe/<slug>/', views.tulinaawe_detail, name="tulinaawe_detail"),
    path('welfare/', views.welfare_view, name="welfare"),
    path('savings-withdraw/', views.savings_withdraw_view, name="savings_withdraw"),
    path('loans/', views.loans_view, name="loans"),
    path('loans/<slug>', views.loan_detail, name="loan_detail"),
    path('loan/application/', views.loan_application_view, name="loan_application"),
    path('loan/application-detail/<slug>', views.loan_application_detail_view, name="loan_application_detail"),
    path('reports/', views.reports_view, name="reports"),
    path('expenses/', views.expenses_view, name="expenses"),
    path('expenses/<slug>/', views.expenses_detail, name="expenses_detail"),
    path('notes/', views.notes_view, name="notes"),

    path('<slug>/<slug2>-new-transaction/', views.member_new_transaction, name='member_new_transaction'),
    path('<slug>/<slug2>-transactions/', views.member_transactions, name="member_transactions"),

    path('<slug>/<slug2>-convert-savings/', views.convert_savings, name="convert_savings"),
    path('<slug>/<slug2>-pay-using-shares/', views.pay_using_shares, name="pay_using_shares"),

    path('new-transaction/', views.new_transaction, name="new_transaction"),
    path('all-transactions/', views.all_transactions, name="all_transactions"),
    path('transaction/<slug>/', views.transaction_view, name="transaction"),

    path('transaction/<slug>/detail/', views.transaction_detail, name="transaction_detail"),

    path('print/', views.print_view, name="print"),

    path('member/', views.member_info, name="member_info"),

    path('member-report/', views.member_report, name="member_report"),
    path('api/reports/', views.reports_api, name="reports_api"),
    path('api/member-report/', views.member_report_api, name="member_report_api"),

    path('settings/', views.settings_view, name="settings"),
]

main/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re


class FinancialYearManager(models.Manager):
	
	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date__range=(start_date, end_date))

class LoanFinancialYearManager(models.Manager):

	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date_created__range=(start_date, end_date))
	

class ExpensesFinancialYearManager(models.Manager):

	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date__range=(start_date, end_date))


class Settings(models.Model):
	id = models.BigAutoField(primary_key=True)
	results_order = models.CharField(max_length=255, default="show last added")

	def __str__(self):
		return "%s"%self.id


class FinancialYear(models.Model):
	id = models.BigAutoField(primary_key=True)
	first_date = models.DateTimeField()
	second_date = models.DateTimeField()
	active = models.BooleanField(default=False)
	settings = models.ForeignKey(Settings, on_delete=models.CASCADE)

	def __str__(self):
		return "%s --> %s"%(self.first_date.date().strftime('%x') ,self.second_date.date().strftime('%x')) 


class Member(models.Model):

	#Choices

	gender_choices = [
		("male", "Male"),
		("female", "Female"),
	]

	marital_status_choices = [
		("single", "Single"),
		("married", "Married")
	]

	source_of_income_choices = [
		("salary", "Salary"),
		("business", "Business"),
		("pension", "Pension")
	]

	business_sector_choices = [
		("transport", "Transport"),
		("hospitality", "Hospitality"),
		("real_estate", "Real Estate"),
		("tourism", "Tourism"),
		("wholesale_retail", "Wholesale / Retail"),
		("financial_services", "Financial Services"),
		("health_care", "Health Care"),
		("manufacturing", "Manufacturing"),
		("education", "Education")
	]

	mode_of_remittance_choices = [
		("check_off", "Check Off"),
		("direct_deposit", "Direct Deposit"),
		("standing_order", "Standing Order"),
		("pay_bill_m_money", "Paybill (M-Money)")
	]



	#Basic Details
	id = models.BigAutoField(primary_key=True)
	code = models.CharField(max_length=255, unique=True)
	image = models.ImageField(blank=False, null=False)
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	full_names = models.CharField(max_length=255, default="")
	contact = models.CharField(max_length=255)
	date_joined = models.DateTimeField()

	#Applicant Details
	email_address = models.EmailField(blank=True)
	residence = models.CharField(max_length=255, blank=True)
	town = models.CharField(max_length=255, blank=True)
	box_no = models.CharField(max_length=255, blank=True)
	town_code = models.CharField(max_length=255, blank=True)
	marital_status = models.CharField(max_length=255, choices=marital_status_choices)
	gender = models.CharField(max_length=255, choices=gender_choices)
	date_of_birth = models.DateTimeField(null=True, blank=True)
	identification_no = models.CharField(max_length=255, blank=True)
	source_of_income = models.CharField(max_length=255, blank=True, choices=source_of_income_choices)

	#Employment Details
	employer = models.CharField(max_length=255, blank=True)
	date_of_employment = models.DateTimeField(null=True, blank=True)
	employment_address = models.CharField(max_length=255, blank=True)
	position_in_employment = models.CharField(max_length=255, blank=True)
	staff_number = models.CharField(max_length=255, blank=True)

	#Business Details
	business_name = models.CharField(max_length=255, blank=True)
	business_address = models.CharField(max_length=255, blank=True)
	business_sector = models.CharField(max_length=255, blank=True, choices=business_sector_choices)
	business_sector_others = models.TextField(blank=True)
	business_location = models.CharField(max_length=255, blank=True)
	business_monthly_income = models.PositiveIntegerField(default=0, blank=True)

	#Remittance
	proposed_monthly_contribution = models.IntegerField(default=0, blank=True)
	effective_date = models.DateTimeField(null=True, blank=True)
	amount_in_words = models.CharField(max_length=255, blank=True)
	mode_of_remittance = models.CharField(max_length=255, blank=True, choices=mode_of_remittance_choices)

	#Totals
	shares = models.IntegerField(default=0)
	welfare = models.IntegerField(default=0)
	savings = models.IntegerField(default=0)
	withdraw = models.IntegerField(default=0)
	fines = models.IntegerField(default=0)
	other = models.IntegerField(default=0)

	#Official Declaration
	data_captured_by = models.CharField(max_length=255, blank=True)
	data_date_capture = models.DateTimeField(null=True, blank=True)
	system_approval_by = models.CharField(max_length=255, blank=True)
	system_approval_date = models.DateField(null=True, blank=True)
	membership_approved_by = models.CharField(max_length=255, blank=True)
	membership_approval_date = models.DateTimeField(null=True, blank=True)
	admitted_by_1 = models.CharField(max_length=255, blank=True)
	admitted_by_1_date = models.DateTimeField(null=True, blank=True)
	admitted_by_2 = models.CharField(max_length=255, blank=True)
	admitted_by_2_date = models.DateTimeField(null=True, blank=True)

	class Meta:
		ordering = ["code"]

	@property
	def date_fields(self):
		return ['date_joined', 'date_of_birth', 'date_of_employment', 'effective_date', 'data_date_capture', 'system_approval_date', 'membership_approval_date', 'admitted_by_1_date', 'admitted_by_2_date']

	@property
	def name_snippet(self):
		if len(self.full_names) > 18:
			return "%s..."%(self.full_names[0:18])
		else:
			return self.full_names

	@property
	def full_name(self):
		return '%s %s'%(self.first_name, self.last_name)

	def clean(self):
		code_pattern = r'KYDI/\d+'
		contact_pattern = r'^\d{10}$'

		match_code = re.match(code_pattern, self.code)
		match_contact = re.match(contact_pattern, self.contact)

		if not match_code:
			raise ValidationError({'code': 'Code should be in the form KYDI/000'})

		if not match_contact:
			raise ValidationError({'contact': 'Invalid Contact'})
	        
	def save(self, *args, **kwargs):
		self.full_names = "%s %s"%(self.first_name, self.last_name)
		self.full_clean()
		return super().save(*args, **kwargs)

	def __str__(self):
		return "%s - %s"%(self.code, self.full_names)



class NomineesForDeposits(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.CharField(max_length=255)
	id_no = models.CharField(max_length=255)
	percentage = models.PositiveIntegerField(default=0)
	date_of_birth = models.DateTimeField()
	mobile_no = models.CharField(max_length=255)

	member = models.ForeignKey(Member, on_delete=models.CASCADE)



class Transaction(models.Model):
	id = models.BigAutoField(primary_key=True)

	fines_choices = [
		("General Meeting", "General Meeting"),
		("Weekly Meeting", "Weekly Meeting"),
		("Late", "Late"),
		("Uniform", "Uniform"),
		("Minimum Savings", "Minimum Savings"),
	]

	date = models.DateTimeField()
	shares = models.IntegerField(default=0)
	welfare = models.IntegerField(default=0)
	savings = models.IntegerField(default=0)
	withdraw = models.IntegerField(default=0)
	fines = models.IntegerField(default=0)
	fine_type = models.CharField(max_length=255, choices=fines_choices, null=True, blank=True)
	other = models.IntegerField(default=0, blank=True)
	notes = models.TextField(blank=True)
	member = models.ForeignKey(Member, on_delete=models.CASCADE)

	objects = FinancialYearManager()

	@property
	def notes_snippet(self):
		return "%s..."%(self.notes[0:70])

	class Meta:
		ordering = ["-date", "member"]

	def __str__(self):
		return "%s: %s %s --> %s"%(self.member.code, self.member.first_name, self.member.last_name, self.date.date())


class TransactionType(models.Model):
	id = models.BigAutoField(primary_key=True)
	general = models.BooleanField(default=False)
	withdraw = models.BooleanField(default=False)
	fined = models.BooleanField(default=False)
	savings_to_shares = models.BooleanField(default=False)
	paid_fines = models.BooleanField(default=False)
	share_pay = models.BooleanField(default=False)

	transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)

	def __str__(self):
		return "%s %s --> %s"%(self.transaction.member.first_name, self.transaction.member.last_name, self.transaction.date.date())


class Tulinaawe(models.Model):
	id = models.BigAutoField(primary_key=True)
	date_due = models.DateTimeField(null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	title = models.CharField(max_length=255)
	description = models.TextField()
	status = models.BooleanField(default=True)
	total_amount_contributed = models.IntegerField(default=0)

	@property
	def title_snippet(self):
		if len(self.title) > 15:
			return "%s..."%(self.title[0:15])
		else:
			return "%s"%(self.title)

	@property
	def description_snippet(self):
		if len(self.description) > 40:
			return "%s..."%(self.description[0:40])
		else:
			return "%s"%(self.description)

	class Meta:
		verbose_name_plural = "Tulinaawe"
		ordering = ["-date_due"]

	def __str__(self):
		return "%s"%(self.title)


class TulinaaweContributor(models.Model):
	id = models.BigAutoField(primary_key=True)
	date = models.DateTimeField(null=True)
	event = models.ForeignKey(Tulinaawe, on_delete=models.CASCADE)
	member = models.ForeignKey(Member, on_delete=models.CASCADE)
	amount = models.IntegerField(default=0)

	def __str__(self):
		return "%s %s -- %s"%(self.member.first_name, self.member.last_name, self.event)


class Loan(models.Model):
	id = models.BigAutoField(primary_key=True)
	member = models.ForeignKey(Member, on_delete=models.CASCADE, blank=True, null=True)

	member_name = models.CharField(max_length=255)
	amount = models.IntegerField(default=0)
	amount_in_words = models.CharField(max_length=255, blank=True)

	#Computed Data
	amount_paid = models.IntegerField(default=0)
	interest = models.IntegerField(default=0)

	date_due = models.DateTimeField()
	date_taken_out = models.DateTimeField()

main/templates/main/loans.html
{% extends 'index.html' %}
{% load static %}
{% load humanize %}

{% block link7 %}
active-link
{% endblock %}

{% block title %}
    <h2 class="border-b-2 border-indigo-500 ml-4 font-semibold text-gray-700">Loans</h2>
{% endblock %}

{% block header %}
	
	<form action="" method="POST" id="comparison-form" class="form-control flex gap-4">
		{% csrf_token %}
		<input type="text" name="member-name" placeholder="Search member">

		<button class="border my-2 px-2 rounded-md">
			<i data-feather="search" class="text-gray-500"></i>
		</button>
		

		<!-- <a href="/print?context=members&ids={{print_ids}}" class="text-gray-500 border px-2 py-1 rounded flex items-center">
			<i data-feather="printer"></i>
		</a> -->
	</form>
{% endblock %}


{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6 pt-4">

		<div>

			<a href="{% url 'main:loan_application' %}" class="button mt-0 ml-0 w-52 mb-4 flex justify-between peer bg-blue-500 hover:bg-blue-600" data-label="form-toggler">
				<span>New Loan Application</span>
				<i data-feather="plus" class="w-5 h-5"></i>
			</a>

			<div class="w-full rounded-lg shadow-xs border bg-white py-2 px-4 mb-4 h-0 hidden" data-label="form-container">

				<form method="POST" action="" class="form-control" id="loan-form">
					{% csrf_token %}
					{{form}}
					<input type="submit" name="submit" value="Submit">
				</form>
			</div>

		</div>

		<div class="py-4 flex gap-2">
			<a href="?action=paid-loans" class="px-4 block text-gray-500 border rounded border-slate-400 py-1">Paid Loans</a>
			<a href="?action=unpaid-loans" class="px-4 block text-gray-500 border rounded border-slate-400 py-1">Unpaid Loans</a>
		</div>

		<div class="w-full rounded-lg shadow-xs border mb-6 p-3 bg-white">

			<div class="flex gap-x-20 flex-wrap">
				
				<div class="flex flex-wrap items-center bg-white rounded-lg shadow-xs  py-1">
					<div class="p-2 self-start mr-3 rounded-full bg-orange-100 text-orange-500">
						<i data-feather="package" class="h-5 w-5"></i>
					</div>
					<div>
						<p class="text-sm font-medium text-gray-600">No. of loans</p>
						<p class="text-base font-semibold text-gray-700">
							{{loans_count}}
						</p>
					</div>
				</div>

				<div class="flex items-center bg-white rounded-lg shadow-xs  py-1">
					<div class="p-2 self-start mr-3 rounded-full bg-green-100 text-green-500">
						<i data-feather="dollar-sign" class="h-5 w-5"></i>
					</div>
					<div>
						<p class="text-sm font-medium text-gray-600">Total Amount Taken Out</p>
						<p class="text-base font-semibold text-gray-700">
							{{total_amount|intcomma}}
						</p>
					</div>
				</div>
				
				<div class="flex items-center bg-white rounded-lg shadow-xs  py-1">
					<div class="p-2 self-start mr-3 rounded-full bg-green-100 text-green-500">
						<i data-feather="dollar-sign" class="h-5 w-5"></i>
					</div>
					<div>
						<p class="text-sm font-medium text-gray-600">Total Amount Paid</p>
						<p class="text-base font-semibold text-gray-700">
							{{total_amount_paid|intcomma}}
						</p>
					</div>
				</div>

				<div class="flex items-center bg-white rounded-lg shadow-xs  py-1">
					<div class="p-2 self-start mr-3 rounded-full bg-green-100 text-green-500">
						<i data-feather="dollar-sign" class="h-5 w-5"></i>
					</div>
					<div>
						<p class="text-sm font-medium text-gray-600">Total Interest Paid</p>
						<p class="text-base font-semibold text-gray-700">
							{{total_interest|intcomma}}
						</p>
					</div>
				</div>
			</div>
		</div>
		
        <div class="w-full rounded-lg shadow-xs border mb-6 overflow-x-hidden">
			<table class="w-full">

				<thead>
					<tr class="text-xs font-bold tracking-wide text-left text-gray-500 border-b bg-row-even">
						<th class="px-4 py-3">Member</th>
						<th class="px-4 py-3">Date Due</th>
						<th class="px-4 py-3">Amount</th>
						<th class="px-4 py-3">Amount Paid</th>
						<th class="px-4 py-3">Balance</th>
						<th class="px-4 py-3">ACTIONS</th>
					</tr>
				</thead>

				<tbody class="bg-white">
	
					{% for loan in loans %}

						<tr class="text-gray-700 border-t even:bg-row-even odd:bg-row-odd">

							<td class="px-4 py-3">
								<div class="flex items-center text-sm">

									{% if loan.member != None %}
									<div class="w-10 h-10 rounded-full relative overflow-hidden">
										<img src="{{loan.member.image.url}}" class="object-fill rounded-full absolute">
									</div>
									{% else %}
									<div class="w-10 h-10 rounded-full relative overflow-hidden">
										<img src="{% static 'images/klogo.png' %}" class="object-fill rounded-full absolute">
									</div>
									{% endif %}

									{% if loan.member != None %}
										<div class="ml-3">
											<p class="font-semibold">
												{{loan.member.name_snippet}}
											</p>
											<p class="text-sm tracking-wide text-gray-500">
												{{loan.member.code}}
											</p>
										</div>
									{% else %}
									<p class="font-semibold ml-3">
										{{loan.member_name|upper}}
									</p>
									{% endif %}
									
								</div>
							</td>

							<td class="px-4 py-3">{{loan.date_due.date}}</td>

							<td class="px-4 py-3">
								{{loan.amount|intcomma}}
							</td>

							<td class="px-4 py-3">
								{{loan.amount_paid|intcomma}}
							</td>

							<td class="px-4 py-3">
								{{loan.balance|intcomma}}
							</td>

							<td class="px-4 py-3">
								<div class="px-2 relative group">
									<a href="{% url 'main:loan_detail' loan.id %}" class="text-indigo-600">
										<i data-feather="maximize-2" class="w-5 h-5"></i>
									</a>
									<span class="tool-tip" style="left: -20%;">
										Expand
									</span>
								</div>
							</td>

						</tr>

					{% endfor %}

				</tbody>

			</table>
			{% if not paid_or_unpaid %}
			{% if page_range %}

				<div class="border-t py-4 px-2 flex justify-end paginator">
					
					<div class="flex text-gray-500">
				
						{% if loans.has_previous %}
							<a href="?page={{loans.previous_page_number}}">
								<i data-feather="chevron-left" class="w-5 h-5"></i>
							</a>
						{% endif %}

						{% for page in page_range %}
							{% if page == loans.number %}
								<a href="?page={{page}}" class="bg-blue-50 text-blue-500">{{page}}</a>
							{% else %}
								<a href="?page={{page}}">{{page}}</a>
							{% endif %}
						{% endfor %}

						{% if loans.has_next %}
							<a href="?page={{loans.next_page_number}}">
								<i data-feather="chevron-right" class="w-5 h-5"></i>
							</a>
						{% endif %}
					</div>

				</div>

			{% endif %}
			{% endif %}

		</div>

	</main>
{% endblock %}

{% block scripts %}
	<script src="{% static 'custom_scripts/loans.js' %}"></script>
{% endblock %}

main/templates/main/member_new_transaction.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6">

		<div class="flex gap-4">
			<h2 class="mt-4 mb-3 text-xl font-semibold text-gray-600">Add Transaction</h2>

			<div class="mt-4 mb-3">

				<button id="general-transaction" class="active-t">
					General Transaction
				</button>

				<button id="other-transaction" class="ml-4 inactive-t">
					Other Transaction
				</button>
			</div>
		</div>

		<div class="w-full rounded-lg shadow-xs border bg-white py-2 px-4 mb-4">
			<input type="hidden" value="{{latest_date|date:"Y-m-d"}}" id="latest_date">
			<form method="POST" action="" id="transaction-add-form" class="form-control">

				{% csrf_token %}
				<input type="hidden" name="user-no-conflict" value="{{user}}">

				<div class="grid grid-cols-2 gap-8">
					<div>

						<div class="text-sm mt-4 pl-1">
							<p data="full-name" class="font-semibold">
								{{member.first_name}} {{member.last_name}}
							</p>
							<div class="w-48 h-48 mt-4">
								<img src="{{member.image.url}}" data="image">
							</div>
						</div>

						<div class="flex gap-4 mt-6">
							<input id="use-last-date" type="checkbox" style="appearance: checkbox; width: 16px; padding: 0; margin: 0; outline: none; border: none;">
							<label for="use-last-date" style="margin:0;">Use previous date</label>
						</div>

						<label for="id_date" style="margin-top: 1.4rem;">Date</label>
						{{form.date}}
						{{form.date.errors}}

						<div data-label="welfare">
							<label for="id_welfare">Welfare</label>
							{{form.welfare}}
							{{form.welfare.errors}}
						</div>

					</div>

					<div data-label="control-1" class="block">

						<label for="id_shares">Shares</label>
						{{form.shares}}
						{{form.shares.errors}}

						<label for="id_savings">Savings</label>
						{{form.savings}}
						{{form.savings.errors}}

						<label for="id_withdraw">Withdraw</label>
						{{form.withdraw}}
						{{form.withdraw.errors}}

						<label for="id_fines">Fines</label>
						{{form.fines}}
						{{form.fines.errors}}

						<label for="id_fine_type">Fine Type</label>
						{{form.fine_type}}
						{{form.fine_type.errors}}

					</div>

					<div data-label="control-2" class="hidden">
						<label for="id_fines">Other</label>
						{{form.other}}
						{{form.other.errors}}

						<label for="id_fine_type">Reason</label>
						{{form.other_reason}}
						{{form.other_reason.errors}}
					</div>
				</div>

				<div class="flex items-center justify-end">
					
					<input class="ml-0" type="submit" name="submit" value="Submit">
					
				</div>

			</form>
		</div>
	</main>
{% endblock %}

{% block scripts %}
	<script src="{% static 'custom_scripts/member_new_transaction.js' %}"></script>
{% endblock %}

main/templates/main/pay_using_shares.html
{% extends 'index.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    <h2 class="border-b-2 border-indigo-500 ml-4 font-semibold text-gray-700">
        Pay Using Shares
    </h2>
{% endblock %}

{% block link2 %}
active-link
{% endblock %}

{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6 pt-4">

		<div class="w-full rounded-lg shadow-xs border bg-white py-2 px-4">

			<form method="POST" action="" id="pay-using-shares-form" class="form-control">
				{% csrf_token %}
				<input type="hidden" name="user-no-conflict" value="{{user}}">
				
				<div>
					<div class="flex mt-4 pl-1">
						<div class="w-44 h-44">
							<img src="{{member.image.url}}" data="image" class="rounded-full">
						</div>
						<div class="ml-6">
							<p class="font-semibold">{{member.full_name}}</p>
							<p>{{member.code}}</p>
							<p>
								<span>Total Shares:</span>
								<span label="total-shares" data="{{member.shares}}">
									{{member.shares}}
								</span>
							</p>
						</div>
					</div>

					<div class="mt-4">
						<label for="id_date">Date</label>
						{{form.date}}
						{{form.date.errors}}

						<label for="id_fines">Shares</label>
						{{form.shares}}
						{{form.shares.errors}}

						<ul class="errorlist">
							<li></li>
						</ul>
					</div>

					<div class="hidden">
						{{form.savings}}
						{{form.withdraw}}
						{{form.welfare}}
                        {{form.fines}}
						{{form.fine_type}}
					</div>
				</div>

				<input type="submit" name="btnSubmit" value="Submit">
			</form>
		</div>
	</main>
{% endblock %}

{% block scripts %}
<script src="{% static 'custom_scripts/pay_using_shares.js' %}"></script>
{% endblock %}

main/templates/main/update_member.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6">


		<div class="w-full rounded-lg shadow-xs border bg-formbg py-2 pb-0 mb-6 mt-4">

            <div class="bg-white py-2 border-b px-4">
                <h2 class="text-base text-gray-600 font-semibold">Edit Member</h2>
            </div>
			{{form.errors}}
			<form method="POST" action="{% url 'main:update_member' %}" id="member-add-form" class="form-control px-4 pt-4" enctype="multipart/form-data">
				{% csrf_token %}
				<input type="hidden" name="user-no-conflict" value="{{user}}">
				
				<div>
					<div class="grid grid-cols-10 gap-10">
						<div class="col-span-6">

							<label for="id_code">Code</label>
							{{form.code}}
							{{form.code.errors}}

							<label for="id_first_name">First Name</label>
							{{form.first_name}}
							{{form.first_name.errors}}

							<label for="id_last_name">Last Name</label>
							{{form.last_name}}
							{{form.last_name.errors}}

							<label for="id_contact">Contact</label>
							{{form.contact}}
							{{form.contact.errors}}

							<label for="id_date_joined">Date Joined</label>
							{{form.date_joined}}
							{{form.date_joined.errors}}
						</div>

						<div class="col-span-4 pt-5 flex items-center">
							{{form.image}}
							{{form.image.errors}}
						</div>

						<div class="col-span-6 hidden">
							<div class="flex">
								{{form.marital_status}}
							</div>
							<div class="flex">
								{{form.gender}}
							</div>
						</div>
					</div>
				</div>
				
			</form>

            <div class="bg-white border-t py-3 flex items-center mt-4">
                <input type="submit" form="member-add-form" value="Submit" class="bg-indigo-500 block text-white px-12 py-2 rounded-md ml-auto mr-4 cursor-pointer hover:bg-indigo-600 transition-colors">
            </div>
            
		</div>
	</main>
{% endblock %}

{% block scripts %}

<script>
	let dateField = document.querySelector("input[name='date_joined']");
	let date = dateField.value.split(' ')[0];

	dateField.setAttribute('type', 'date');
	dateField.value = date;
</script>

{% endblock %}